### ISSUE TITLE
Add support for fish shell

### ISSUE THREAD

**Issue by afarinetti** [zekroTJA/goup#10]
Would it be possible to add support for the `fish` shell?

**Comment by zekroTJA** [comment]
Hey! Yeah, that shouldn't be a huge deal. [`whattheshell`](https://github.com/zekroTJA/whattheshell), the underlying crate to detect the shell environment, already supports fish. I only would need to do some research on how to assemble the environment variable command because I've never used fish so far.

**Comment by zekroTJA** [comment]
Hey, sorry for the long silence on this, but I've now found the time and motivation to add fish support, which will be included in the next release (v1.6.0).

![WindowsTerminal_xqWu6mGsWI](https://github.com/zekroTJA/goup/assets/16734205/e737922f-8495-4ff4-82ad-3edfdf565ecc)

While implementing for fish, I somewhat started to like the way this shell works. Maybe I'll give it a try on my own setups. :D

**Comment by afarinetti** [comment]
Very nice, thank you very much!
